# Generated by Django 6.0.2 on 2026-02-13 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_section_remove_product_purchase_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricing',
            name='marked_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='selling_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
