# Generated by Django 6.0.2 on 2026-02-15 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_sale_marked_price_snapshot_alter_sale_profit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_purchase_rate', models.BooleanField(default=True)),
            ],
        ),
    ]
