# Generated by Django 5.2.12 on 2026-04-04 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_category_options_alter_category_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='systemsettings',
            options={'verbose_name': 'System Setting', 'verbose_name_plural': 'System Settings'},
        ),
    ]
