# Generated by Django 5.2.12 on 2026-04-05 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_systemsettings_options'),
        ('store', '0011_pricing_size_based'),
    ]

    operations = [
    ]
