# Generated by Django 5.2.12 on 2026-04-05 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_merge_20260405_1849'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricing',
            options={'verbose_name_plural': 'Pricings'},
        ),
        migrations.AlterUniqueTogether(
            name='pricing',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='marked_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Leave blank to auto-calculate (purchase rate × 1.5)', max_digits=10, null=True),
        ),
    ]
