# Generated by Django 5.2.12 on 2026-04-05 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_remove_pricing_unique_constraint'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stock',
            unique_together=set(),
        ),
    ]
