# Generated by Django 5.2.12 on 2026-04-06 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_sale_sold_date_to_datefield'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='customer_name',
            field=models.CharField(blank=True, help_text='Customer name (required for Due sales)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='customer_phone',
            field=models.CharField(blank=True, help_text='Customer phone (required for Due sales)', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='due_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Amount pending if payment is Due', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='is_due',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sale',
            name='payment_mode',
            field=models.CharField(choices=[('cash', 'Cash'), ('phonepay', 'PhonePe'), ('due', 'Due (Pay Later)')], default='cash', max_length=10),
        ),
    ]
