# Generated by Django 5.2.12 on 2026-04-06 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_sale_customer_name_sale_customer_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='pricing_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
